version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: labseq-backend
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_HTTP_HOST=0.0.0.0
      - QUARKUS_HTTP_CORS_ORIGINS=http://localhost:4200,http://localhost:80
    networks:
      - labseq-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/labseq/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: labseq-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - labseq-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  labseq-network:
    driver: bridge